microsoft/workshop-library

covid-paper-exploration-workshop/COVIDPaperExploration.ipynb, covid-paper-exploration-workshop/COVIDPaperExplorationDetailed.ipynb, covid-paper-exploration-workshop/solution/COVIDPaperExploration.ipynb
- Added plotly install command in the solution file.
- Added plotly install instruction comment in both non-solution files.
- Fixed small error on printing the abstracts' analyze result that was noticed by Dmitry during TTT session.
=> Added Plotly install command

static-web-apps-short/README.md
=> adding README

full/covid-paper-text-analytics/README.md, full/covid-paper-text-analytics/solution/COVIDPaperExploration.ipynb
=> Remove service keys and make wording more clear

README.md
I went through the videos that had start times as text and got them mapped to the link itself. This will help anyone that is clicking in the link and wants to see the actual section (instead of searching for the start time)
=> use youtube links with start times

full/deep-learning-computer-vision/README.md
=> Make minor fixes to Deep Learning workshop following MLSA TTT

.github/workflows/gitguardian.yml
Partially helps with issue #62
=> prevent git guarding from running on forks

.github/workflows/gitguardian.yml
=> editing workflow to check for pushes only to main

.github/workflows/gitguardian.yml, workshop-suggestions.md
=> Test branch

workshop-suggestions.md
=> testing a workflow

full/intro-nlp-tensorflow/README.md, full/intro-nlp-tensorflow/translations/README.md, full/intro-nlp-tensorflow/translations/es/README.es.md
Includes a small tweak to the README so that it includes the video
=> Spanish translations for NLP

full/intro-nlp-tensorflow/translations/es/README.es.md
Seems like my translation managed to break the table. This PR should fix that problem
=> fix table on nlp spanish readme

full/power-app-custom-vision/README.md
=> fixed some typo in the README.md. The link on "Instructions on how to create a great video experience" is broken, returns 404

full/mood-journal-progressive-web-app/1-create-pwa.md, full/mood-journal-progressive-web-app/README.md, full/mood-journal-progressive-web-app/solution/02-repose/src/script/pages/app-home.ts
Updated to include slides for PWA workshop
=> Add slides to PWA workshop

full/build-resume-website/translations/es/0-instalacion.md, full/build-resume-website/translations/es/1-crear-html.md, full/build-resume-website/translations/es/2-anadir-contenido.md, full/build-resume-website/translations/es/3-anadir-estilo.md, full/build-resume-website/translations/es/4-creando-una-pagina-web.md, full/build-resume-website/translations/es/README.md, full/build-resume-website/translations/es/diseno-del-taller.md
=> ES translation OK

full/intro-minapi/README.md
Updates to existing readme with code fixes and additional explanation.
=> Minimal API workshop readme fixes

short/intro-static-web-apps/translations/README.md, short/intro-static-web-apps/translations/es/README.es.md
Path to files:
`./short/intro-static-web-apps/translations`
ES translation:
`../translations/es/README.es.md`
=> Add ES translations for Introduction to Azure Static Web Apps

es/index.md, index.md
=> Add soft skills

es/index.md
Workshop that was translated into spanish: Build a Machine Learning Model using Azure Custom Vision. I included the link in the index.md file
=> updated the link of a workshop that was translated into Spanish

short/public-speaking/translations/README.md, short/public-speaking/translations/pt-br/README.md
Translation of public speaking readme to pt-br
=> Translation PT-BR

full/explore-analyze-data-with-R/translations/es/README.md, full/explore-analyze-data-with-R/translations/es/solution/challenge-Data_Exploration.ipynb, full/explore-analyze-data-with-R/translations/es/solution/tests/Question 6.R, full/explore-analyze-data-with-R/translations/es/solution/tests/Question 7.R, full/explore-analyze-data-with-R/translations/es/solution/tests/Question 8.R, full/explore-analyze-data-with-R/translations/es/solution/tests/Question 9.R, full/explore-analyze-data-with-R/translations/es/workshop-designer.md
Pull request for the issue #118 , let me your comments @abrilurena 😄
=> Spanish translation for Explore and analyze data with R

es/index.md
I fixed the links from the main readme file and I added a new workshop that has been translated into spanish.
=> fixed links and added a new workshop

full/explore-analyze-data-with-R/translations/es/README.md, full/intro-databricks/translations/es/README.md, full/intro-nlp-tensorflow/translations/es/README.md, full/power-platform-canvas-app/translations/es/README.md
Por el momento arregle los links del taller de "explora y analiza datos con R" debido a que quiero promover este taller con los demas ambassadors en whatsapp
=> arregle links de taller de felipe + video

short/intro-static-web-apps/translations/README.md, short/intro-static-web-apps/translations/pt-br/README.md, short/public-speaking/translations/pt-br/README.md
Translation of static web app to PT-BR
=> Translation of static web app to PT-BR

full/power-platform-canvas-app/translations/pt-br/README.md, short/intro-github-dev/translations/pt-br/README.md, short/intro-static-web-apps/translations/pt-br/README.md
=> Added two translations to PT-BR and fixed links in a third one to reflect localized versions

full/build-resume-website/translations/README.md, full/build-resume-website/translations/es/README.md, short/intro-static-web-apps/translations/README.md
- fixed broken links from different workshops.
- changed "Build your resume" workshop structure and fixed links.
=> fixed broken links

full/mood-journal-progressive-web-app/translations/README.md, full/mood-journal-progressive-web-app/translations/es/0-instalación.md, full/mood-journal-progressive-web-app/translations/es/1-crear-pwa.md, full/mood-journal-progressive-web-app/translations/es/2-agregar-contenido.md, full/mood-journal-progressive-web-app/translations/es/3-despliegue-en-Azure.md, full/mood-journal-progressive-web-app/translations/es/4-agregar-manifiesto-web.md, full/mood-journal-progressive-web-app/translations/es/5-registrar-trabajador-de-servicio.md, full/mood-journal-progressive-web-app/translations/es/6-notificaciones.md, full/mood-journal-progressive-web-app/translations/es/7-listo-para-la-tienda.md, full/mood-journal-progressive-web-app/translations/es/README.md, full/mood-journal-progressive-web-app/translations/es/workshop-designer.md
**Workshop translated:** Mood journal progressive web app.
- **Files translated**
- All workshop markdown files.
- Powerpoint Slides.
Issue #192
=> #192 Spanish Translations - Mood journal progressive web app

full/a-gentle-introduction-to-Azure-AI/README.md
Added a section to Gentle Intro to AI workshop to include a bonus section on how to encourage audience participation.
Detailed how to use Microsoft Forms Poll feature to create questions
Pointed to speaker notes in ppt and video run through to show delivery
=> Adding Microsoft Forms Poll Bonus section to Gentle Intro to AI Workshop

full/a-gentle-introduction-to-Azure-AI/README.md, full/a-gentle-introduction-to-Azure-AI/solution/README.md
=> Adding note for non-Azure OpenAI endpoints support in the workshop demo
